<?php

namespace AppBundle\Repository;

/**
 * ConceptoGastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoGastoRepository extends \Doctrine\ORM\EntityRepository
{
}
