<?php

namespace AppBundle\Repository;

/**
 * FichaCostoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichaCostoRepository extends \Doctrine\ORM\EntityRepository
{
}
