<?php

namespace AppBundle\Repository;

/**
 * ModalidadPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalidadPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
