<?php

namespace AppBundle\Repository;

/**
 * ProductoModalidadPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoModalidadPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
