<?php

namespace AppBundle\Repository;

/**
 * VentaProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
